// Generated by CoffeeScript 1.4.0
(function() {
  var setup;

  $(function() {
    var pre, _i, _len, _ref, _results;
    console.log("edit", this, $("pre"));
    _ref = $("pre");
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      pre = _ref[_i];
      _results.push(setup(pre));
    }
    return _results;
  });

  setup = function(pre) {
    var $textarea, $textarea2, cm1, cm2, code, recompile, text;
    code = $(pre).find("code");
    text = code.text();
    $textarea = $("<textarea>" + text + "</textarea>");
    $textarea2 = $("<textarea>....</textarea>");
    $(pre).replaceWith($textarea);
    $textarea.after($textarea2);
    console.log($textarea.get(0));
    cm1 = CodeMirror.fromTextArea($textarea.get(0), {
      lineNumbers: true,
      viewportMargin: Infinity,
      lineWrapping: true
    });
    cm2 = CodeMirror.fromTextArea($textarea2.get(0), {
      lineNumbers: true,
      viewportMargin: Infinity,
      readOnly: true,
      lineWrapping: true,
      mode: "html"
    });
    recompile = function() {
      var FOOTER, HEADER, coffeescript, javascript;
      coffeescript = cm1.getValue();
      HEADER = "{html, body, ol, render, div, span, table, thead, tbody, tr, td, th, text, textarea, button, hr, iframe,\n raw, a, br, b, img, label, form, input, ul, li, h1, h2, h4, select, option, p} = window.onecup\n";
      FOOTER = "window.output = window.onecup.render()";
      javascript = CoffeeScript.compile(HEADER + coffeescript + FOOTER);
      console.log("change", javascript);
      eval(javascript);
      console.log("html", window.output);
      return cm2.setValue(window.output);
    };
    recompile();
    return cm1.on("change", function() {
      return recompile();
    });
  };

}).call(this);
